### ISSUE TITLE
Вопросы к реализации

### ISSUE THREAD

**Issue by VitaliyDemchuk** [VVSite/drupal8test#1]
- [x] Запуск проекта не возможен без файлов `docker-compose.yml`, `.env`. Нужно добавить их в репозиторий и обеспечить запуск проекта через docker-compose без дополнительных действий.
- [x] Использование иконочных шрифтов (Material icons, font-awesome)?
- [x] Использование flexbox?
- [x] Использование методологии БЭМ?
- [x] [Использование jQuery и нативного js](https://github.com/VVSite/drupal8test/blob/744a6bb88cc44306d8d374d43af6478e5f14b59f/web/modules/todolist/js/todolist.js#L14). В чем заключается основная идея по использованию гибридного подхода, а не простого jQuery, например `$(tdl).attr('data-id', id);`?

**Comment by VVSite** [comment]
Иконочные шрифты в проекте не используются.

**Comment by VVSite** [comment]
Файлы `docker-compose.yml`, `.env` включены в репозиторий.

**Comment by VVSite** [comment]
`flexbox` не использовался в проекте, разметка выполнена другими CSS - инструкциями. Если бы стояла задача выполнить TODO List в виде карточек - тогда да.

**Comment by VitaliyDemchuk** [comment]
> Иконочные шрифты в проекте не используются.

А в принципе, когда-то использовались?

**Comment by VitaliyDemchuk** [comment]
> `flexbox` не использовался в проекте, разметка выполнена другими CSS - инструкциями. Если бы стояла задача выполнить TODO List в виде карточек - тогда да.

Интересно узнать, был ли опыт использования? Или может CSS grid?

**Comment by VVSite** [comment]
> > Иконочные шрифты в проекте не используются.
> 
> А в принципе, когда-то использовались?

Да, делаю https://naska.su/ В интерфейсе используется font-awesome.

**Comment by VVSite** [comment]
> > `flexbox` не использовался в проекте, разметка выполнена другими CSS - инструкциями. Если бы стояла задача выполнить TODO List в виде карточек - тогда да.
> 
> Интересно узнать, был ли опыт использования? Или может CSS grid?

Был, для одного проекта делал что-то типа просмотра галлереи в виде карточек (рисунки с надписями).

**Comment by VVSite** [comment]
> В чем заключается основная идея по использованию гибридного подхода, а не простого jQuery, например `$(tdl).attr('data-id', id);`?
Это требование начальства - обрабатывать data-аттрибуты таким образом. Я просто спешил и не сразу вспомнил, что присвоение нужно делать так $( tdl ).data( "id", 52 ); а в коде через dataset элемента. Это некрасиво конечно.

**Comment by VitaliyDemchuk** [comment]
> > > Иконочные шрифты в проекте не используются.
> > 
> > 
> > А в принципе, когда-то использовались?
> 
> Да, делал https://naska.su/ В интерфейсе используется font-awesome. В др.проектах тоже

Принял.

**Comment by VitaliyDemchuk** [comment]
> > В чем заключается основная идея по использованию гибридного подхода, а не простого jQuery, например `$(tdl).attr('data-id', id);`?
> 
> Это требование **бывшего** начальства - обрабатывать data-аттрибуты таким образом. Я просто спешил и не сразу вспомнил, что присвоение нужно делать так $( tdl ).data( "id", 52 ); а в коде через dataset элемента. Это некрасиво конечно.
> 
> UPD: ну и API jQuery как-бы рекомендует: https://api.jquery.com/data/

Это хорошо)
